<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * 2 new tables: PhotoStats and UserStats
 */
class Version20121102193745 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE PhotoStats (timestamp INT NOT NULL, statusCount_ALL INT NOT NULL, responsesCount_UNANSWERED INT NOT NULL, responsesCount_INCOMPLETE INT NOT NULL, responsesCount_COMPLETE INT NOT NULL, responsesCount_PHOTO_PROBLEM INT NOT NULL, medianDuration DOUBLE PRECISION NOT NULL, photoId INT NOT NULL, INDEX IDX_5CF899142738825 (photoId), PRIMARY KEY(photoId, timestamp)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE UserStats (timestamp INT NOT NULL, responsesCount_UNANSWERED INT NOT NULL, responsesCount_INCOMPLETE INT NOT NULL, responsesCount_COMPLETE INT NOT NULL, responsesCount_PHOTO_PROBLEM INT NOT NULL, medianDuration DOUBLE PRECISION NOT NULL, userId INT NOT NULL, INDEX IDX_33D3F6DF64B64DCC (userId), PRIMARY KEY(userId, timestamp)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE PhotoStats ADD CONSTRAINT FK_5CF899142738825 FOREIGN KEY (photoId) REFERENCES Photo (id)");
        $this->addSql("ALTER TABLE UserStats ADD CONSTRAINT FK_33D3F6DF64B64DCC FOREIGN KEY (userId) REFERENCES User (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE PhotoStats");
        $this->addSql("DROP TABLE UserStats");
    }
}
