<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * PhotoResponse submittedAt (DateTime → timestamp/int)
 */
class Version20121102191157 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE PhotoResponse ADD submittedAt2 INT DEFAULT NULL");
        $this->addSql("UPDATE PhotoResponse SET submittedAt2 = unix_timestamp(submittedAt)");
        $this->addSql("ALTER TABLE PhotoResponse DROP COLUMN submittedAt");
        $this->addSql("ALTER TABLE PhotoResponse CHANGE submittedAt2 submittedAt INT DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE PhotoResponse ADD submittedAt2 DATETIME DEFAULT NULL");
        $this->addSql("UPDATE PhotoResponse SET submittedAt2 = from_unixtime(submittedAt)");
        $this->addSql("ALTER TABLE PhotoResponse DROP COLUMN submittedAt");
        $this->addSql("ALTER TABLE PhotoResponse CHANGE submittedAt2 submittedAt DATETIME DEFAULT NULL");
    }
}
